services:
  app:
    build: 
      context: .
    ports:
      - "8000:8081" 
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
    depends_on:
      - postgresql
    env_file:
      - ./.env
    networks:
      - app-network
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_2:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge